### ISSUE TITLE
Refactoring .gitignore

### ISSUE THREAD

**Issue by ruppysuppy** [amder111/self_driving_car#2]
A lot of the file types in the [.gitignore](https://github.com/amder111/self_driving_car/blob/master/.gitignore) is redundant. It can be optimized by removing them (for example [django stuff](https://github.com/amder111/self_driving_car/blob/master/.gitignore#L54))

**Comment by abhirupmjdr** [comment]
okay... create a pull request after fixing it... I'll merge it.
